### ISSUE TITLE
Truncating of text

### ISSUE THREAD

**Issue by willmcgugan** [wasi-master/rich-rst#1]
Rich-rst seems to truncate text at the right edge for some reason. I've attached a screenshot.

Let me know if you need any assistance re the Rich API.

<img width="1058" alt="Screen Shot 2022-02-09 at 09 25 26" src="https://user-images.githubusercontent.com/554369/153165796-19b1fec5-0769-4813-b415-17387ea543c8.png">
.

**Comment by wasi-master** [comment]
yeah I would like some assistance with the rich API. The line that adds those text is this line

```python
def visit_Text(self, node):
    style = self.console.get_style("restructuredtext.text", default="none")
    self.renderables.append(Text(node.astext().replace("\n", " "), end="", style=style))
```

https://github.com/wasi-master/rich-rst/blob/main/rich_rst/__init__.py#L124-L126

And the code for showing the renderables is as follow

```python
for renderable in visitor.renderables:
    yield from console.render(renderable, options)
```

https://github.com/wasi-master/rich-rst/blob/main/rich_rst/__init__.py#L525-L526

So what should I do to fix that issue 🤔

**Comment by wasi-master** [comment]
I just tested it a bit and it seems a bit weird. The text in the blue circle is truncated but the text in the red one is

![image](https://user-images.githubusercontent.com/63045920/153208451-ade43037-fb69-4130-b8cb-d4a2e58449a4.png)

**Comment by willmcgugan** [comment]
I suspect the root of the problem is that the way you yield Text objects with `end=""`. This may render them 0from the end, but it won't allow them to wrap.

To wrap text, you will need to extend the Text objects. i.e. by calling Text.append. Then when you have all the text you can yield it.

**Comment by willmcgugan** [comment]
Fantastic, Rich-CLI should pick the latest release so no update required :)

**Comment by wasi-master** [comment]
\:)
